spring.application.name=ecommerce-api-sb13
server.port=1333

# Database or Datasource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13usr
spring.datasource.password=qwerqwer
spring.datasource.url=jdbc:postgresql://localhost:1300/sb13_db

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
media.location=/Users/chanchhaya/Documents/sb13-media-upload/
media.client-path=/media
media.base-uri=http://localhost:1333