#spring.security.user.name=istad
#spring.security.user.password=qwerqwer
#spring.security.user.roles=STAFF

spring.application.name=ecommerce-api-sb13
spring.profiles.active=prod

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.threads.virtual.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
media.location=/Users/chanchhaya/Documents/sb13-media-upload/
media.client-path=/media
media.base-uri=http://localhost:1333

keycloak.server-url=http://localhost:1301
keycloak.realm=ecommerce
keycloak.client-id=private-app
keycloak.client-secret=758eBiHix0sBcNXYafRC0j3F3p7Z1L5e