server.port=8080

# Database or Datasource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13usr
spring.datasource.password=92ee7381de214c275dfef08a5581beeaee63925cd121c0a2
spring.datasource.url=jdbc:postgresql://47.237.144.245:1300/ecommerce_qa_db