server.port=1333

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:1301/realms/ecommerce
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:1301/realms/ecommerce/protocol/openid-connect/certs

# Database or Datasource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13usr
spring.datasource.password=qwerqwer
spring.datasource.url=jdbc:postgresql://localhost:1300/ecommerce_db