spring.application.name=ecommerce-api-sb13
server.port=1333

# Database or Datasource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13usr
spring.datasource.password=qwerqwer
spring.datasource.url=jdbc:postgresql://localhost:1300/sb13_db

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true